fix(gha): fix branch detection error
from e.g. https://github.com/spinnaker/fiat/actions/runs/13405954400/job/37445817517

Run BRANCHES=$(git branch -r --contains refs/tags/v1.54.0)
BRANCHES is '  origin/HEAD -> origin/master
  origin/master'
NUM_BRANCHES is '2'
exactly one branch required to release fiat, but there are 2 (  origin/HEAD -> origin/master
  origin/master)
Error: Process completed with exit code 1.